import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "@/lib/auth";
import { sql } from "@/lib/db";
type Ctx={params:Promise<{id:string}>};
const allowedTypes=new Set(["certificate","application_letter","transcript","contract","identity_document","other"]);
const allowedMime=new Set(["application/pdf","image/jpeg","image/png","image/webp","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
export async function GET(_r:NextRequest,{params}:Ctx){try{await requireRole(["Administrator","HR Officer"]);const {id}=await params;const documents=await sql`SELECT d.id,d.employee_id,d.document_type,d.title,d.file_name,d.mime_type,d.file_size,d.notes,d.created_at,u.full_name uploaded_by_name FROM employee_documents d LEFT JOIN users u ON u.id=d.uploaded_by WHERE d.employee_id=${id}::uuid ORDER BY d.created_at DESC`;return NextResponse.json({success:true,documents});}catch(error){console.error(error);return NextResponse.json({success:false,message:"Unable to load employee documents."},{status:500});}}
export async function POST(request:NextRequest,{params}:Ctx){try{const user=await requireRole(["Administrator","HR Officer"]);const {id}=await params;const form=await request.formData();const file=form.get("file");const documentType=String(form.get("documentType")||"");const title=String(form.get("title")||"").trim();const notes=String(form.get("notes")||"").trim()||null;if(!(file instanceof File)||!title||!allowedTypes.has(documentType))return NextResponse.json({success:false,message:"Select a valid document, type and title."},{status:400});if(!allowedMime.has(file.type))return NextResponse.json({success:false,message:"Allowed files: PDF, JPG, PNG, WEBP, DOC and DOCX."},{status:400});if(file.size>10*1024*1024)return NextResponse.json({success:false,message:"Document must not exceed 10 MB."},{status:400});const employee=await sql`SELECT id FROM employees WHERE id=${id}::uuid LIMIT 1`;if(!employee.length)return NextResponse.json({success:false,message:"Employee not found."},{status:404});const base64=Buffer.from(await file.arrayBuffer()).toString('base64');const rows=await sql`INSERT INTO employee_documents(employee_id,document_type,title,file_name,file_data,mime_type,file_size,notes,uploaded_by) VALUES(${id}::uuid,${documentType},${title},${file.name},decode(${base64},'base64'),${file.type},${file.size},${notes},${user.userId}::uuid) RETURNING id,employee_id,document_type,title,file_name,mime_type,file_size,notes,created_at`;await sql`INSERT INTO audit_logs(user_id,action,module_name,record_id,new_values) VALUES(${user.userId}::uuid,'Uploaded employee document','Employees',${id},${JSON.stringify({documentType,title,fileName:file.name})}::jsonb)`;return NextResponse.json({success:true,message:"Document uploaded successfully.",document:rows[0]},{status:201});}catch(error){console.error(error);return NextResponse.json({success:false,message:"The document could not be uploaded."},{status:500});}}
export async function DELETE(request:NextRequest,{params}:Ctx){try{const user=await requireRole(["Administrator"]);const {id}=await params;const documentId=request.nextUrl.searchParams.get("documentId");if(!documentId)return NextResponse.json({success:false,message:"Document ID is required."},{status:400});const rows=await sql`DELETE FROM employee_documents WHERE id=${documentId}::uuid AND employee_id=${id}::uuid RETURNING id,title`;if(!rows.length)return NextResponse.json({success:false,message:"Document not found."},{status:404});await sql`INSERT INTO audit_logs(user_id,action,module_name,record_id,old_values) VALUES(${user.userId}::uuid,'Deleted employee document','Employees',${id},${JSON.stringify(rows[0])}::jsonb)`;return NextResponse.json({success:true,message:"Document deleted successfully."});}catch(error){console.error(error);return NextResponse.json({success:false,message:"The document could not be deleted."},{status:500});}}
