"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Role={id:string;name:string};
type User={id:string;full_name:string;email:string;status:string;must_change_password:boolean;last_login_at:string|null;created_at:string;role_name:string};

type Props={initialUsers:User[];roles:Role[]};

export default function UserManager({initialUsers,roles}:Props){
  const router=useRouter();
  const [users,setUsers]=useState(initialUsers);const [fullName,setFullName]=useState("");const [email,setEmail]=useState("");const [roleId,setRoleId]=useState("");const [temporaryPassword,setTemporaryPassword]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState(false);const [busy,setBusy]=useState(false);
  async function createUser(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const res=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName,email,roleId,temporaryPassword})});const data=await res.json();if(!res.ok||!data.success){setError(true);setMessage(data.message||'Unable to create user.');return;}setUsers((u)=>[...u,data.user].sort((a,b)=>a.full_name.localeCompare(b.full_name)));setFullName('');setEmail('');setRoleId('');setTemporaryPassword('');setError(false);setMessage(`User created. Temporary password: ${data.temporaryPassword}`);router.refresh();}catch{setError(true);setMessage('Unable to connect to the server.');}finally{setBusy(false)}}
  async function action(id:string,act:string){if(act==='delete'&&!confirm('Delete this user account?'))return;setMessage('');try{const res=await fetch(`/api/users/${id}`,{method:act==='delete'?'DELETE':'PATCH',headers:{'Content-Type':'application/json'},body:act==='delete'?undefined:JSON.stringify({action:act})});const data=await res.json();if(!res.ok||!data.success){setError(true);setMessage(data.message||'Action failed.');return;}if(act==='delete')setUsers(u=>u.filter(x=>x.id!==id));else if(act==='suspend'||act==='activate')setUsers(u=>u.map(x=>x.id===id?{...x,status:data.status}:x));setError(false);setMessage(data.temporaryPassword?`${data.message} Temporary password: ${data.temporaryPassword}`:data.message);router.refresh();}catch{setError(true);setMessage('Unable to connect to the server.')}}
  return <div className="space-y-8">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8">
      <div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black text-slate-900">Add System User</h2><p className="mt-1 text-sm text-slate-500">Create an account and assign a specific role. New users must change their password on first login.</p></div><div className="rounded-2xl bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700">Administrator only</div></div>
      <form onSubmit={createUser} className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <div><label className="mb-2 block text-sm font-bold text-slate-700">Full name</label><input value={fullName} onChange={e=>setFullName(e.target.value)} required className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100"/></div>
        <div><label className="mb-2 block text-sm font-bold text-slate-700">Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100"/></div>
        <div><label className="mb-2 block text-sm font-bold text-slate-700">Role</label><select value={roleId} onChange={e=>setRoleId(e.target.value)} required className="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="">Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>
        <div><label className="mb-2 block text-sm font-bold text-slate-700">Temporary password</label><input value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)} placeholder="Leave blank to auto-generate" className="w-full rounded-xl border border-slate-300 px-4 py-3"/></div>
        <div className="md:col-span-2 xl:col-span-4"><button disabled={busy} className="rounded-xl bg-blue-700 px-6 py-3 font-black text-white shadow-sm hover:bg-blue-800 disabled:opacity-60">{busy?'Creating...':'Create User'}</button></div>
      </form>
      {message&&<div className={`mt-5 rounded-xl border px-4 py-3 text-sm font-semibold ${error?'border-red-200 bg-red-50 text-red-700':'border-green-200 bg-green-50 text-green-700'}`}>{message}</div>}
    </section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-black text-slate-900">System Users</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-slate-50 text-sm text-slate-600"><tr>{['User','Role','Status','First-login Password','Last Login','Actions'].map(h=><th key={h} className="px-6 py-4">{h}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-slate-100"><td className="px-6 py-4"><p className="font-black text-slate-900">{u.full_name}</p><p className="mt-1 text-sm text-slate-500">{u.email}</p></td><td className="px-6 py-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{u.role_name}</span></td><td className="px-6 py-4 capitalize"><span className={`rounded-full px-3 py-1 text-xs font-black ${u.status==='active'?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{u.status}</span></td><td className="px-6 py-4">{u.must_change_password?'Required':'Completed'}</td><td className="px-6 py-4">{u.last_login_at?new Date(u.last_login_at).toLocaleString('en-GB'):'Never'}</td><td className="px-6 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>action(u.id,u.status==='active'?'suspend':'activate')} className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-black text-amber-700">{u.status==='active'?'Suspend':'Activate'}</button><button onClick={()=>action(u.id,'reset-password')} className="rounded-lg border border-blue-200 px-3 py-2 text-xs font-black text-blue-700">Reset Password</button><button onClick={()=>action(u.id,'delete')} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700">Delete</button></div></td></tr>)}</tbody></table></div></section>
  </div>
}
